using Microsoft.AspNetCore.Mvc;

namespace Nexus_Service_Marketing.Models
{
    public class Bill
    {
        public int BillId { get; set; }

        public int OrderId { get; set; }
        public Order Order { get; set; }

        // 💰 Base plan amount
        public decimal PlanAmount { get; set; }

        // 🎁 Discount
        public decimal DiscountAmount { get; set; }   // e.g. bulk / scheme

        // 🧾 Tax
        public decimal TaxPercentage { get; set; }     // 12.24
        public decimal TaxAmount { get; set; }

        public decimal Amount { get; set; }
        public DateTime BillDate { get; set; }
        public DateTime DueDate { get; set; }

        public bool IsPaid { get; set; }

        // 👩‍💻 Generated by
        public string GeneratedBy { get; set; }

        // Navigation property
        public ICollection<Payment> Payments { get; set; }
    }

}
